services:
  mongo:
    image: mongo:7
    container_name: taskflow-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - taskflow-mongo-data:/data/db

volumes:
  taskflow-mongo-data:
